// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://turpgllifkrhguozmnul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1cnBnbGxpZmtyaGd1b3ptbnVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTc1MzMsImV4cCI6MjA3NDczMzUzM30.NN9KGW_jV0jgKDyha8zX5lGdSDlZOMI2f1oni3BMxjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});